# IP 段来源（Cloudflare 官方，支持镜像）
IPV4_SOURCE = "https://www.cloudflare-cn.com/ips-v4/"
IPV6_SOURCE = "https://www.cloudflare-cn.com/ips-v6/"

downloadBytes = 1024 * 1024 * 20
previousCountry = "HK"

DEFAULT_CSV_OUTPUT = "{path}/bestips-{date}{num}.csv"
DEFAULT_IP_OUTPUT = "./ip.txt"
OUTPUT_FOLDER_PATH = "./output/{date}"
DEFAULT_THREADS = 2 #测可用性的线程数，这是一个适合自动化服务的数字。
MAX_IO_THREADS = 100 #建议不要超过这个数字。
DEFAULT_SPEED_WORKERS = 5 #假设每个ip能跑到10MB/S，大概是能占满500Mbps的带宽。

#当链接中没有{bytes}时，该程序只会下载downloadBytes的量。
SPEED_TEST_URL = "https://speed.cloudflare.com/__down?during=download&bytes={bytes}"
# 可能有些反代只反代了cloudflare官网，怎么改看你。
AVAILABILITY_URL = "https://www.cloudflare.com/cdn-cgi/trace"
AVAILABILITY_HOST = "www.cloudflare.com"

PING_COUNT = 4
PING_TIMEOUT_SEC = 2
CURL_TIMEOUT_SEC = 5
SPEED_TEST_TIMEOUT = 20
MAX_LATENCY_MS = 300.0
MIN_SPEED_MBPS = 1.0
DEBUG = False
LOG_FILE = None

