#https://github.com/forestfirefox/cloudflare-sni-proxy-tester

# ipinfo token 用于线路、国家查询。需要自己填充。
token = ""

#----【警告】
# 不要把这个数字设得很大!
# 20MB完全够你测速了！
# 不要滥用反代IP占用资源！
downloadBytes = 1024 * 1024 * 20 #20MB

previousCountry = "" # 可不填，此时以HK为默认值

#traceroute hops
hops = 30

# 是否只在ip.txt中输出高级线路
ONLY_OUTPUT_BEST_ROUTE = true;

DEFAULT_INPUT = "./ip.csv"

# 以下{date}映射日期，可不填，格式：YYYY-MM-DD；
# 	   {num}为文件名重复时的填充，没有{num}时：如果文件名重复将直接覆盖。

DEFAULT_IP_OUTPUT = "./ip.txt" #为了方便自动化服务，默认直接覆盖这个文件
DEFAULT_CSV_OUTPUT = "{path}/bestips-{date}{num}.csv" 
OUTPUT_FOLDER_PATH = "./output/{date}" #可以写"./"

DEFAULT_THREADS = 2 #测可用性的线程数，这是一个适合自动化服务的数字。
MAX_IO_THREADS = 100 #建议不要超过这个数字。
DEFAULT_SPEED_WORKERS = 5 #假设每个ip能跑到10MB/S，大概是能占满500Mbps的带宽。

#当链接中没有{bytes}时，该程序只会下载downloadBytes的量。
SPEED_TEST_URL = "https://speed.cloudflare.com/__down?during=download&bytes={bytes}"
# 可能有些反代只反代了cloudflare官网，怎么改看你。
AVAILABILITY_URL = "https://www.cloudflare.com/cdn-cgi/trace"
AVAILABILITY_HOST = "www.cloudflare.com"

PING_COUNT = 4
PING_TIMEOUT_SEC = 2
CURL_TIMEOUT_SEC = 5

SPEED_TEST_TIMEOUT = 20
MAX_LATENCY_MS = 300.0
MIN_SPEED_MBPS = 1.0
TRACEROUTE_TIMEOUT = 35

DEBUG = False #调试模式：显示每个ip的剔除原因及系统命令输出。
LOG_FILE = None #输出日志文件